export enum FILE_TYPE_ENUM {
  '.pdf' = '.pdf',
  '.doc' = '.doc',
  '.docx' = '.docx',
  '.xls' = '.xls',
  '.xlsx' = '.xlsx',
  '.ppt' = '.ppt',
  '.pptx' = '.pptx',
  '.txt' = '.txt',
  '.csv' = '.csv',
  '.jpg' = '.jpg',
  '.jpeg' = '.jpeg',
  '.png' = '.png',
  '.gif' = '.gif',
  '.svg' = '.svg',
  '.mp4' = '.mp4',
  '.avi' = '.avi',
  '.mov' = '.mov',
  '.wmv' = '.wmv',
}
